title: "Roberto Tejada Arevalo"
tagline: "Planetary interiors & exoplanet evolution"
theme: minima           # or minimal-mistakes-jekyll, al-folio, etc.
author:
  name: "Rob Tejada"
  email: "arevalo(at)princeton.edu"
  google_scholar: "https://scholar.google.com/citations?user=XXXX"
